### PR TITLE
Feature/deposit service test

### PR DESCRIPTION
**Pull request by Pl8tinium**
create service test for testing the deposit/ withdraw workflow

### CODE REVIEW

**Comment by vaultec81** [comment]
TODO (for me):
- [ ] Fix new block streaming transfer formatting
- [ ] Multisig withdrawel logic

**Comment by Pl8tinium** [comment]
> TODO (for me):
> 
> * [ ]  Fix new block streaming transfer formatting
> * [ ]  Multisig withdrawel logic

finalizeBalanceUpdate in chainBridge.ts was thought of to vaguely resemble something that the deciding multisig node would call in order to finalize the withdraw

**Comment by vaultec81** [comment]
I need to do a bit more testing on my end on the multisig and make sure everything is working there, then come back to this and test out the full flow.

**Comment by vaultec81** [comment]
@Pl8tinium Can you refactor this to match latest? I will merge in after then to further testing/development on my end

**Comment by Pl8tinium** [comment]
> @Pl8tinium Can you refactor this to match latest? I will merge in after then to further testing/development on my end

rebased from main

**Comment by vaultec81** [comment]
Thank you!

**Pull request merged**
